[2024-01-17T21:05:12.886-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cities_coleta_teste.df scheduled__2024-01-18T00:03:59.135588+00:00 [queued]>
[2024-01-17T21:05:12.889-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cities_coleta_teste.df scheduled__2024-01-18T00:03:59.135588+00:00 [queued]>
[2024-01-17T21:05:12.889-0300] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-17T21:05:12.897-0300] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): df> on 2024-01-18 00:03:59.135588+00:00
[2024-01-17T21:05:12.901-0300] {standard_task_runner.py:57} INFO - Started process 106597 to run task
[2024-01-17T21:05:12.903-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'cities_coleta_teste', 'df', 'scheduled__2024-01-18T00:03:59.135588+00:00', '--job-id', '2917', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphqye9v3f']
[2024-01-17T21:05:12.904-0300] {standard_task_runner.py:85} INFO - Job 2917: Subtask df
[2024-01-17T21:05:12.923-0300] {task_command.py:416} INFO - Running <TaskInstance: cities_coleta_teste.df scheduled__2024-01-18T00:03:59.135588+00:00 [running]> on host desktop
[2024-01-17T21:05:12.951-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='datasetpibic@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cities_coleta_teste' AIRFLOW_CTX_TASK_ID='df' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T00:03:59.135588+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-18T00:03:59.135588+00:00'
[2024-01-17T21:05:13.402-0300] {logging_mixin.py:154} INFO - Called | 1705536313.399849 | df
[2024-01-17T21:05:13.409-0300] {logging_mixin.py:154} INFO - SAVING FILE df
[2024-01-17T21:05:13.410-0300] {python.py:194} INFO - Done. Returned value was: None
[2024-01-17T21:05:13.413-0300] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=cities_coleta_teste, task_id=df, execution_date=20240118T000359, start_date=20240118T000512, end_date=20240118T000513
[2024-01-17T21:05:13.475-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-17T21:05:13.481-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
